name: senior_launcher
description: A lightweight launcher for seniors.

version: 1.5.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.1.0
  contacts_service: ^0.4.6
  device_apps: ^1.1.0
  flutter_downloader: ^1.5.2
  flutter_icons: ^1.1.0
  flutter_webview_plugin: ^0.3.11
  fluttertoast: ^7.1.6
  http: ^0.12.2
  intl: ^0.16.1
  pedantic: ^1.9.2
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
